---
roles:
  - name: gantsign.antigen
    version: 1.3.2
  - name: geerlingguy.composer
    version: 1.7.6
  - name: geerlingguy.git
    version: 2.1.0
  - name: geerlingguy.mysql
    version: 3.1.0
  - name: geerlingguy.php
    version: 4.3.0
  - name: geerlingguy.php-mysql
    version: 2.0.2
  - name: geerlingguy.php-versions
    version: 4.0.3
  - name: geerlingguy.php-xdebug
    version: 3.0.0
  - name: geerlingguy.redis
    version: 1.6.0
