---
- name: install dependencies
  become: yes
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - zsh
    - tar
    - gzip

- name: create download directory
  file:
    path: '{{ antigen_download_dir }}'
    state: directory
    mode: 'u=rwx,go=rx'

- name: download Antigen
  get_url:
    url: '{{ antigen_redis_mirror }}/{{ antigen_redis_filename }}'
    dest: '{{ antigen_download_dir }}/{{ antigen_local_filename }}'
    sha256sum: '{{ antigen_redis_sha256sum }}'
    mode: 'u=rw,go=r'

- name: create install directory
  become: yes
  become_user: '{{ item.username }}'
  file:
    path: '~{{ item.username }}/.antigen'
    state: directory
    mode: 'u=rwx,go=rx'
  with_items: '{{ users }}'

- name: install Antigen
  become: yes
  unarchive:
    src: '{{ antigen_download_dir }}/{{ antigen_local_filename }}'
    remote_src: yes
    dest: '~{{ item.username }}/.antigen'
    extra_opts:
      - '--strip-components=1'
    creates: '~{{ item.username }}/.antigen/antigen.zsh'
    owner: '{{ item.username }}'
    mode: 'go-w'
  with_items: '{{ users }}'

- name: install oh-my-zsh
  include_tasks: install-oh-my-zsh.yml
  when: antigen_install_oh_my_zsh
