---
- hosts: all
  become: yes

  vars_files:
    - ./vars/vars.yml

  vars_prompt:
    - name: symfony_env
      prompt: "Enter the environment for your Symfony app (prod|test|dev)"
      default: dev
      private: no

  environment:
    SYMFONY_ENV: "{{ symfony_env|lower }}"

  pre_tasks:
    - name: Convert entered Symfony enviroment to lowercase
      set_fact:
        symfony_env: "{{ symfony_env|lower }}"
      tags:
        - always

    - name: Install aptitude
      become: true
      apt:
        name: aptitude

    - name: Update APT package repositories
      become: true
      apt:
        update_cache: yes

    - name: Upgrade installed packages
      become: true
      apt:
        upgrade: safe

  roles:
    - nginx
    - role: geerlingguy.git
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.composer
    - role: geerlingguy.mysql
    - role: geerlingguy.php-mysql
    - role: geerlingguy.php-xdebug
    - role: geerlingguy.redis
    - role: gantsign.antigen
      users:
        - username: "{{ ansible_user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: af-magic
          antigen_bundles:
            # Autosuggestions bundle.
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions

  tasks:
    - ping: ~

    - name: Install low-level Utils
      become: true
      apt:
        name: "{{ item }}"
      with_items:
        - zip
        - unzip

    - name: add enabled site to /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ server_name }}"
        line: "127.0.0.1 {{ server_name }}"

    - name: Set SSH home directory.
      lineinfile:
        dest: "/home/{{ ansible_user }}/.bashrc"
        state: present
        create: yes
        regexp: "^SSH_HOME="
        line: "SSH_HOME={{ ssh_home }} && [ -e $SSH_HOME ] && cd $SSH_HOME"
      become: no
      when: ssh_home is defined

    - name: Set Zsh SSH home directory.
      lineinfile:
        dest: "/home/{{ ansible_user }}/.zshrc"
        state: present
        create: yes
        regexp: "^SSH_HOME="
        line: "SSH_HOME={{ ssh_home }} && [ -e $SSH_HOME ] && cd $SSH_HOME"
      become: no
      when: ssh_home is defined

  handlers:
    - name: Restart PHP-FPM
      become: true
      service:
        name: php{{ php_version }}-fpm
        state: restarted
