---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        home: '/home/{{ item }}'
        createhome: yes
      with_items:
        - test_usr1
        - test_usr2
        - test_usr3

    - name: install console-setup file
      become: yes
      copy:
        src: tests/console-setup.sh
        dest: /etc/default/console-setup
        force: no
        owner: root
        group: root
        mode: 'u=rwx,go=r'

  roles:
    - role: ansible_role_antigen
      users:
        - username: test_usr1
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: ant
              url: robbyrussell/oh-my-zsh
              location: plugins/ant
        - username: test_usr2
          antigen_libraries:
            - name: prezto
              args:
                - '--verbose'
              env:
                ENV_TEST1: 'testValue1'
          antigen_theme:
            name: testTheme1
            url: https://example.com/testTeme1.git
          antigen_bundles:
            - name: mvn
              args:
                - '--no-local-clone'
              env:
                ENV_TEST2: 'testValue2'
            - name: gradle
              url: https://example.com/gradle.git
              branch: master
              tag: '1.0'
              args:
                - '--no-local-clone'
              env:
                ENV_TEST3: 'testValue3'
            - name: sdkman
              url: '$HOME/.sdkman-zsh'
            - name: escape
              url: 't\e"s"ti\ng`pwd`test2$(pwd)'
        - username: test_usr3
